import React, { useState } from 'react';
import axios from 'axios';

const Setup2FA = ({ qr, userId, onNext, onLogin }) => {
  const [token, setToken] = useState('');
  const [status, setStatus] = useState('Scan the QR code with your authenticator app and enter the code below.');
  const [error, setError] = useState('');

  const handleConfirm = async (e) => {
    e.preventDefault();
    try {
      const res = await axios.post('/api/auth/confirm-2fa', {
        userId,
        token
      });
      if (res.data?.token) {
        localStorage.setItem('token', res.data.token);
        setStatus('2FA setup complete. Redirecting to your dashboard...');
        setError('');
        if (onLogin) {
          onLogin();
        } else {
          onNext('dashboard');
        }
      }
    } catch (err) {
      setError(err.response?.data?.msg || '2FA verification failed');
      setStatus('Please try again.');
    }
  };

  return (
    <div className="auth-page">
      <div className="auth-card">
        <div className="auth-left">
          <div className="auth-head">
            <h2>Set up Authenticator 2FA</h2>
            <p>{status}</p>
          </div>
          <div className="auth-form">
            {qr ? (
              <img src={qr} alt="Authenticator QR code" style={{ width: '100%', maxWidth: '320px', borderRadius: '20px', marginBottom: '1rem', border: '1px solid rgba(129, 86, 255, 0.18)' }} />
            ) : (
              <p>Loading QR code...</p>
            )}
            {error && <p className="error-text">{error}</p>}
            <form onSubmit={handleConfirm}>
              <input
                type="text"
                placeholder="Enter authenticator app code"
                value={token}
                onChange={(e) => setToken(e.target.value)}
                required
              />
              <button type="submit">Confirm 2FA</button>
            </form>
            <p className="auth-note">
              <button type="button" className="link-button" onClick={() => onNext('login')}>
                Skip for now and login
              </button>
            </p>
          </div>
        </div>
        <div className="auth-right">
          <h3>Secure your login</h3>
          <p>Use an authenticator app to protect your account with stronger login verification. This step adds an additional security layer beyond your password.</p>
          <div className="accent-box">
            <h4>How it works</h4>
            <ul>
              <li>Scan the code with an app like Google Authenticator.</li>
              <li>Enter the one-time code generated by the app.</li>
              <li>Secret setup keys are hidden from the UI for stronger security.</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Setup2FA;
